--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount> (select avg(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) from customer
group by item_purchased
order by avg(review_rating) desc
limit 5 ;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select avg(purchase_amount), shipping_type from customer
where shipping_type IN ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select avg(purchase_amount), sum(purchase_amount), Subscription_Status from customer 
where Subscription_Status IN ('Yes','No')
group by Subscription_Status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(avg(case when discount_applied='Yes' then 100.0 else 0.0 end)::numeric,2) as discount_percentage  from customer
group by item_purchased
order by  discount_percentage desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
SELECT 
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment,
	COUNT(*) AS "Number of Customers"
FROM customer
group by 1;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select Subscription_Status, count(*) from customer
where previous_purchases>5 and Subscription_Status In ('Yes','No')
group by Subscription_Status;

--Q10. What is the revenue contribution of each age group? 
select sum(purchase_amount), age from customer
group by age
order by sum(purchase_amount) desc;

